"use client";

import { useState } from "react";

export default function ImageGenerator() {
  const [prompt, setPrompt] = useState("");
  const [image, setImage] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  async function generateImage() {
    if (!prompt.trim()) {
      setError("Please describe the image you want to create.");
      return;
    }

    try {
      setLoading(true);
      setError("");
      setImage("");

      const response = await fetch("/api/image", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ prompt }),
      });

      const data = await response.json();

      if (!response.ok) {
        throw new Error(
          data.error || "Something went wrong while generating the image."
        );
      }

      if (!data.image) {
        throw new Error("No image was returned from the server.");
      }

      setImage(`data:image/png;base64,${data.image}`);
    } catch (err) {
      console.error(err);
      setError(
        err instanceof Error
          ? err.message
          : "Something went wrong while generating the image."
      );
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      style={{
        background: "#111111",
        border: "1px solid rgba(34,197,94,0.3)",
        borderRadius: "16px",
        padding: "20px",
        marginTop: "20px",
      }}
    >
      <h2
        style={{
          color: "#ffffff",
          fontSize: "22px",
          marginBottom: "8px",
        }}
      >
        🖼️ AI Image Generator
      </h2>

      <p
        style={{
          color: "#aaaaaa",
          marginBottom: "18px",
          lineHeight: "1.5",
        }}
      >
        Create flyers, advertisements, business graphics, social media images,
        posters and more.
      </p>

      <textarea
        value={prompt}
        onChange={(e) => setPrompt(e.target.value)}
        placeholder="Example: Create a professional flyer for a POS business in Nigeria with a modern green and black design."
        rows={5}
        maxLength={2000}
        aria-label="Image description prompt"
        style={{
          width: "100%",
          padding: "14px",
          borderRadius: "10px",
          border: "1px solid #333",
          background: "#181818",
          color: "#ffffff",
          resize: "vertical",
          fontSize: "15px",
          boxSizing: "border-box",
        }}
      />

      <button
        onClick={generateImage}
        disabled={loading}
        aria-busy={loading}
        style={{
          width: "100%",
          marginTop: "14px",
          padding: "14px",
          borderRadius: "10px",
          border: "none",
          background: loading ? "#444" : "#22c55e",
          color: "#000000",
          fontWeight: "bold",
          fontSize: "16px",
          cursor: loading ? "not-allowed" : "pointer",
        }}
      >
        {loading ? "Creating your image..." : "Generate Image ✨"}
      </button>

      {error && (
        <p
          style={{
            color: "#ff6b6b",
            marginTop: "15px",
          }}
        >
          {error}
        </p>
      )}

      {image && (
        <div style={{ marginTop: "20px" }}>
          <img
            src={image}
            alt="Generated by TapBomba AI"
            style={{
              width: "100%",
              borderRadius: "12px",
              display: "block",
            }}
          />

          <div
            style={{
              display: "flex",
              justifyContent: "center",
              gap: "12px",
              marginTop: "12px",
              alignItems: "center",
            }}
          >
            <p style={{ color: "#22c55e", margin: 0 }}>
              ✨ Created by TapBomba AI
            </p>
            <a
              href={image}
              download="tapbomba-ai-image.png"
              style={{
                color: "#22c55e",
                textDecoration: "underline",
                fontSize: "14px",
              }}
            >
              Download
            </a>
          </div>
        </div>
      )}
    </div>
  );
}